### ISSUE TITLE
When will the code release? 

### ISSUE THREAD

**Issue by hdadong** [setarehc/diffusion-motion-inbetweening#2]

**Comment by jiatianzhi** [comment]
......

**Comment by hljwkwm** [comment]
Looking forward to your code being open-sourced, hoping the date won't be postponed again!

**Comment by setarehc** [comment]
Code will be released under the MIT license.

**Comment by PeterWangyi** [comment]
Hello author, can it be published this month?

**Comment by setarehc** [comment]
Hi all,

The first version of the code is now available.

Thanks for your patience and intereset,
Setareh

**Comment by tucker666** [comment]
> Hi all,
> 
> The first version of the code is now available.
> 
> Thanks for your patience and intereset, Setareh

really appreciate you staying up until 2 AM to get the code released
