### ISSUE TITLE
Folder `dataset/HumanML3D_abs` is missing

### ISSUE THREAD

**Issue by JasonNero** [setarehc/diffusion-motion-inbetweening#3]
Hi there, thanks a lot for your work, I'm eager to get it up and running locally!

I noticed the `dataset/HumanML3D_abs` folder is missing, I'll just go ahead and clone it from GMD for now. 
Could you add it to this repo as well?

Thanks!

**Comment by setarehc** [comment]
Hi Jason,

Thanks for bringing this to my attention. `dataset/` folder is now added to the repo.

Best,
Setareh
