### ISSUE TITLE
What does `guided-motion-diffusion` refer to?

### ISSUE THREAD

**Issue by indigolxy** [setarehc/diffusion-motion-inbetweening#4]
Hello Team,

I hope this message finds you well. I am currently setting up the project and I've encountered some problems about this script:
```
cd ..
git clone https://github.com/EricGuo5513/HumanML3D.git
unzip ./HumanML3D/HumanML3D/texts.zip -d ./HumanML3D/HumanML3D/
cp -r HumanML3D/HumanML3D guided-motion-diffusion/dataset/HumanML3D
cd guided-motion-diffusion
cp -a dataset/HumanML3D_abs/. dataset/HumanML3D/
```
The script refers to a directory named `guided-motion-diffusion`. Does this directory belong to the GMD repo that needs to be cloned, or should it already exist within the current repository structure? Could you please clarify whether I need to clone the GMD repository for guided-motion-diffusion?

**Comment by setarehc** [comment]
Hi,

Thank you for bringing this to our attention. You are correct, `guided-motion-diffusion` should be replaced with `diffusion-motion-inbetweening` (that section of README was copied from the GMD repository). We've now updated the README with the correct instructions.

Best,
Setareh
