### ISSUE TITLE
Customised input

### ISSUE THREAD

**Issue by mia-y-w** [setarehc/diffusion-motion-inbetweening#8]
Hi @setarehc, thank you for the amazing work! 

I am trying to test it myself and I have some problems producing the right results. 

Here are my settings:

1. I didn't download and process all the datasets, but only HumanAct12 from HumanML3D. 
2. Because I don't have all the processed data, I changed the test.txt file so that it only searches for particular motion clips.
3. I also tried to upload my own motion clip and process it in the same way as other datasets. (i checked how it the motion looks by plotting it, the uploaded motion can be processed correctly, at least i couldn't see any problem)
4. here is how I run it: python -m sample.conditional_synthesis \
    --model_path ./save/condmdi_randomframes/model000750000.pt \
    --edit_mode benchmark_sparse \
    --transition_length 30 \
    --num_samples 1 \
    --num_repetitions 1 \
    --text_prompt "a person is walking" \
    --output_dir ./save/results/condmdi_randomframes/test_results 

By using the command i just mentioned, and specify a particular motion clip (from processed HumanAct12) in the test.txt, I got this result: 
https://github.com/setarehc/diffusion-motion-inbetweening/assets/105863291/e2f447da-2f74-4f73-ab33-c8fd2cfbc8f6
The generation doesn't look very smooth

So I used the visualisation script, but the results are even more weird. here is how one of the .obj file look like: 
<img width="567" alt="Screenshot 2024-07-02 at 09 28 33" src="https://github.com/setarehc/diffusion-motion-inbetweening/assets/105863291/fa64f3a2-d7b1-4118-b05a-db444d9946e6">

My question is: 
1. will changing test.txt affect the generation results? 
2. does the model work with a customised motion clip as input? 
3. Can you give me some guidance to check what has gone wrong, please?

Thank you so much!!!

**Comment by setarehc** [comment]
Hi @mia-y-w! 

Thanks for your interest in our work! 

My guess is that your motion clip doesn't have the same representation format as our version of HumanML3D (global-root representation). My first recommendation is making sure you run the dataset preparation instuctions on your motion clip as listed [here](https://github.com/setarehc/diffusion-motion-inbetweening?tab=readme-ov-file#b-full-data-text--motion-capture). In general, for any custom dataset you want to use, you should export the rotations and positions of your motions and arrange them as a list per frame as in HumanML3D dataset with the global-root representation.

Best,
Setareh

**Comment by mia-y-w** [comment]
I did go through the data preparation process stated in the instructions, both HumanML 3D data and my own data are processed using the script. In the video clip I showed in the link, the input animation is from HumanAct12 which is part of HumanML3D. Does the input animation look ok to you? I don't know how to verify if the data processing is correct. I plotted them, it looks ok. How did you check if your processing was correct using GDM's processing script?

Also, I thought humanML3D was using global joint positions on all the datasets, it doesn't have any rotation data. the non-processed data is (22,3), The author of HumanML3D says it is 22 joints and 3 represents its coordinates. Did I miss something there, where do I need the rotation data?

**Comment by setarehc** [comment]
There seems to be an orientation mismatch between your motion clip and the our motion representation based on your visualization.

You can load your custom motion clips, and run the sample processing (to go from the redundant 263-dim motion representation to 22x3 representation) and visualization lines (visualize the processed motion clip) from any of the sampling scripts (e.g. `sample/synthesize.py`). It will look something like this:
```
# convert redundant representation to global
n_joints = 22 if (sample.shape[1] in [263, 264]) else 21
sample = sample.cpu().permute(0, 2, 3, 1)
sample = data.dataset.t2m_dataset.inv_transform(sample).float()
sample = recover_from_ric(sample, n_joints, abs_3d=args.abs_3d)
sample = sample.view(-1, *sample.shape[2:]).permute(0, 2, 3, 1) # batch_size, n_joints=22, 3, n_frames

# visualize
plot_3d_motion(animation_save_path, skeleton, sample.transpose(2, 0, 1)[:length], dataset, title, fps)
```

I'm not familiar with the details of HumanAct12 dataset. Raw HumanML3D data is presented as Nx22x3 with N frames, 22 joints, and 3 xyz global positions. After being processed, motion data is represented as Nx263 where the 263 includes root position and orientation, rest of the joints' positions, orientations and velocities, as well as the foot contacts. Details of this representation used in our work are provided in Appendix A and B in the [paper](https://arxiv.org/pdf/2405.11126).

- Setareh
